openapi: 3.0.1
x-amazon-apigateway-minimum-compression-size: 1024
info:
  title: Nozoma pms api
  description: This is an api for nozoma pms
  version: '2021-03-11T13:53:22Z'
servers:
  - url: 'http://localhost:8080'
paths:
  /carts:
    $ref: './docs/cart/endpoint-carts.yml'
  /carts/{id}/products:
    $ref: './docs/cart/endpoint-cart-products.yml'
  /carts/{id}:
    $ref: './docs/cart/endpoint-cart-id.yml'