AWSTemplateFormatVersion: "2010-09-09"
Description: Practice 1
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        USERNAME: Jordi
        NODE_OPTIONS: --enable-source-maps
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  ###############################
  #### API GATEWAY          #####
  ###############################

  ApiGatewayRestApi2:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'develop'
      MinimumCompressionSize: 1024
      OpenApiVersion: '3.0.1'
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: .dist/docs/swagger.yml

  AllowExecuteLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-api-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-allow-execute-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-*'


  ###############################
  ####   Dynamo Database    #####
  ###############################

  Dynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-pms-dynamodb-table'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH

  DynamodbCart:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-cart-dynamodb-table'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH

  ###############################
  ####      EVENT BUS       #####
  ###############################

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${AWS::StackName}-event-bus"

  # Define the event pattern, specify the patterns, and the bus used
  CreateProductEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Create product event"
      EventBusName: !Sub "${AWS::StackName}-event-bus"
      EventPattern:
        source:
          - "backoffice.product.ProductCreatedEvent"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "CreateProductLambda"
              - "Arn"
          Id: "CreateProductServiceTarget"

  # Resource that grants permission to EventBridge to invoke the target.
  CreateProductLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "CreateProductLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "CreateProductEventRule"
          - "Arn"

  ###############################
  ####      LAMBDA         #####
  ###############################

  CreateProductLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-create-product-controller'
      Handler: create-product.handler
      CodeUri: .dist/webpack
      Environment:
        Variables:
          TABLE_NAME: !Sub '${AWS::StackName}-pms-dynamodb-table'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource:
                - !GetAtt Dynamodb.Arn
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !Sub '${Dynamodb.Arn}/index/*'

  PostControllerCartLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-post-cart-controller'
      Handler: post-cart-controller.handler
      CodeUri: .dist/webpack
      Environment:
        Variables:
          TABLE_NAME: !Sub '${AWS::StackName}-cart-dynamodb-table'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource:
                - !GetAtt DynamodbCart.Arn
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !Sub '${DynamodbCart.Arn}/index/*'
            - Effect: Allow
              Resource: '*'
              Action:
                - events:PutEvents